### ISSUE TITLE
Release erstellen, im Installer veröffentlichen und Küken entfernen

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/minify_images#1]
Es gibt offenbar noch kein Release im Installer. Wollen wir eins machen, oder ist das AddOn noch nicht produktionsfertig?

**Comment by phoebusryan** [comment]
Ich nutze es bereits produktiv. Müsste es einfach mal in den Installer packen. Ich habs einfach mal nur hier hochgeladen, damit evtl. Feedback kommt...

**Comment by olien** [comment]
Feedback: SUPER!

**Comment by eaCe** [comment]
Habe das AddOn gestern getestet. Nutze ImageOptimizer und es funktioniert **prima**. 
Würde das ganze auch gerne im Installer sehen. 👍

**Comment by staabm** [comment]
Ping

**Comment by schuer** [comment]
Vorm Release bitte einmal die externen Packages im vendor-Ordner auf aktuellen Stand bringen und das AddOn kurz durchtesten.

**Comment by schuer** [comment]
Vendors schonmal geupdatet. Noch testen, dann Release.

**Comment by staabm** [comment]
Ggf macht es sinn die tests bzw Tests ordner im vendor zu löschen damit das addon nicht so eine große filesize hat

Im rex core nutzen wir dafür ein kleines bash file, damit es nicht vergessen wird wenn wieder in 6 monaten das jemand macht

https://github.com/redaxo/redaxo/blob/master/redaxo/bin/update-requirements

**Comment by schuer** [comment]
Guter Hinweise, @staabm. Aber ich will das Ding jetzt einfach mal raushauen, damit hier nicht dauerhaft 20 Küken rumschwirren, um die sich niemand kümmert.

Für alle Feinheiten und Features danach: PR welcome!

**Comment by schuer** [comment]
(Test-Ordner werfe ich aber noch raus)
