### ISSUE TITLE
Manuelle Präferenz Optimierungstool

### ISSUE THREAD

**Issue by alexwenz** [FriendsOfREDAXO/minify_images#2]
War bei einem Testlauf etwas von der geringen Komprimierung verglichen mit dem tinyPNG-Online-Service überrascht.

Ein Vögelchen (Wolfgang) hat mir gezwitschert, dass das Tool so arbeitet, dass immer dem auf dem Server installierten Optimierer Vorrang gegeben wird, auch wenn man explizit "Tinify" ausgewählt und einen Tinify-Key eingeben hat. 

Stimmt das? Wenn ja wäre es toll, wenn man das umgehen könnte bzw. explizit Tinify einschalten kann.

**Comment by schuer** [comment]
Das stimmt nicht ganz, sondern es wird explizit der eine Dienst verwendet, der ausgewählt wurde. Sollte der aus verschiedenen Gründen nicht funktionieren, wird das Bild wie üblich von REDAXO mittels GD generiert. (Tipp: Ins Systemlog schauen, ob dort was steht. Wenn nicht, wurde optimiert.)

Die Qualität wird, sofern der Dienst das anbietet, so verwendet, wie in den Einstellungen des Media Managers hinterlegt. Tinify jedoch nimmt hier keine Parameter an.

**Comment by schuer** [comment]
Achso ja, und Version 2 wurde eben veröffentlicht.
